---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandhar-app
  namespace: clone
  labels:
    app: mandhar-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mandhar-app
  template:
    metadata:
      labels:
        app: mandhar-app
    spec:
      containers:
      - name: amazone-prime-container
        image: shrikant0786/amazon-prime:4
        ports:
        - containerPort: 3000
...
